### ISSUE TITLE
Project Setup

### ISSUE THREAD

**Issue by Lorenz-127** [Lorenz-127/Breakout-Game#1]
### Acceptance Criteria
- Godot 4.3 project is created and properly structured
- GitHub repository is set up with a README and .gitignore
- Project can be successfully opened and run in Godot 4.3

### Tasks
- [x] Install Godot 4.3
- [x] Create a new Godot project
- [x] Set up GitHub repository
- [x] Create initial project structure (folders for scenes, scripts, assets)
- [x] Add README with project description
- [x] Create and push initial commit
