### ISSUE TITLE
Create Death Zone

### ISSUE THREAD

**Issue by Lorenz-127** [Lorenz-127/Breakout-Game#17]
### Acceptance Criteria
- Death zone is created at the bottom of the screen
- Ball entering the death zone triggers life loss
- Death zone does not interfere with normal gameplay

### Tasks
- [x] Create a Death Zone scene with an Area2D node
- [x] Position the death zone at the bottom of the game screen
- [x] Implement signal connection for ball entering the death zone
- [x] Test death zone functionality with ball collision
