### ISSUE TITLE
Implement Basic Scoring System

### ISSUE THREAD

**Issue by Lorenz-127** [Lorenz-127/Breakout-Game#19]
### Acceptance Criteria
- Breaking a brick awards points to the player
- Current score is updated in real-time
- Score persists between levels (if applicable)

### Tasks
- [x] Create a scoring system in the GameManager script
- [x] Assign point values to different brick types
- [x] Implement score increase when a brick is destroyed
- [x] Update HUD to display current score
