### ISSUE TITLE
Create Neon-Themed Brick Sprites

### ISSUE THREAD

**Issue by Lorenz-127** [Lorenz-127/Breakout-Game#26]
### Acceptance Criteria
- At least 3 different brick designs are created (normal, hard, special)
- Brick designs clearly indicate their type and durability
- Brick graphics are consistent with the neon theme
- Brick sprites are optimized for performance

### Tasks
- [ ] Design normal brick sprite
- [ ] Design hard brick sprite
- [ ] Design special brick sprite
- [ ] Implement color variations for each brick type
- [ ] Create damaged states for multi-hit bricks
- [ ] Optimize brick sprites for performance
- [ ] Update TileMap to use new brick sprites
