### ISSUE TITLE
Create Basic Brick System

### ISSUE THREAD

**Issue by Lorenz-127** [Lorenz-127/Breakout-Game#4]
### Acceptance Criteria
- Bricks are displayed on the screen
- Ball collides with bricks
- Bricks disappear when hit by the ball

### Tasks

- [x] Create basic brick texture and tile
- [x] Implement ball-brick collision detection
- [x] Add brick destruction mechanism
- [x] Update score when brick is destroyed (basic implementation)
