### ISSUE TITLE
Create Main Menu

### ISSUE THREAD

**Issue by Lorenz-127** [Lorenz-127/Breakout-Game#8]
### Acceptance Criteria
- Main menu is displayed when the game is launched
- Menu has "Start Game" and "Quit" options
- Selecting an option performs the corresponding action

### Tasks
- [x] Design main menu layout
- [x] Create main menu scene with buttons
- [x] Implement button functionality (start game, quit)
