### ISSUE TITLE
Implement Level Loading System

### ISSUE THREAD

**Issue by Lorenz-127** [Lorenz-127/Breakout-Game#9]
### Acceptance Criteria
- Levels can be defined using a data structure (e.g., 2D array)
- Level data can be loaded into the game
- Bricks are placed according to the level data

### Tasks
- [ ] Design level data structure
- [ ] Create sample level data for testing
- [ ] Implement level loading function
- [ ] Integrate level loading with TileMapLayer for brick placement
- [ ] Test with multiple level layouts
